### ISSUE TITLE
lang issue on web speech api

### ISSUE THREAD

**Issue by bakeiro** [AurelioDeRosa/HTML5-API-demos#8]
### Hello! 
The demo at https://www.audero.it/demo/speech-synthesis-api-demo.html is not working, every languaje sound **always** as english (on google chrome last version), i also try the web speech api (with your examples on sitepoint.com) and the **lang** atribute is not working.

**Comment by AurelioDeRosa** [comment]
Both the demos have been updated. Thank you for reporting this.
