### ISSUE TITLE
Not working in chrome 

### ISSUE THREAD

**Issue by Pritam738** [AurelioDeRosa/HTML5-API-demos#9]
notification net working in chrome browser. working in firefox only. help

**Comment by AurelioDeRosa** [comment]
I just tested the demo and it works correctly. Provide more details of the issue you're experiencing.

**Comment by Pritam738** [comment]
I am stuck at sync gateway
XMLHttpRequest cannot load http://localhost:4984/db/. No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://127.0.0.1:8080' is therefore not allowed access.
bundle.js:17576 The reg ID is ::
 cZo2gTgIurw:APA91bG2WJ8nVGCB3XJrOqHkWNdiLc0ivYmDlkn-rKnCQG9FasHql-szhy-4XE9vw_fLhj09zja0_SloZNG8ioXh2t45qc3FNL9uI54Ybn0YvxmtEgHrUJI3bnFw0dP2hD51K8Ga-tYG

**Comment by Pritam738** [comment]
and i also can't create new custom notifications
